### ISSUE TITLE
App Idea: Capsule + Zerodev

### ISSUE THREAD

**Issue by adeets-22** [capsule-org/examples-hub#16]
Description: Build a simple app that uses [Zerodev](https://zerodev.app/) for account abstraction and Capsule. Leverage the [Zerodev example guide](https://docs.usecapsule.com/account-abstraction/zerodev) to do this.

Use Case: For example, allow users to login with their social accounts via Capsule and enable gas sponsorships or bundled transactions through Zerodev.

**Comment by MrRaccxxn** [comment]
Hi! Can i be assigned to this issue?

**Comment by adeets-22** [comment]
Awesome, just assigned you!

**Comment by adeets-22** [comment]
Hey @MrRaccxxn - any update on this?

**Comment by MrRaccxxn** [comment]
Got issues with my laptop, but finally okay again! Will push the PR this weekend

**Comment by adeets-22** [comment]
Woohoo! Sounds good :)

**Comment by MrRaccxxn** [comment]
One question related to the issue: Should we implement a complete new project like "with-next-pimlico", or implement this as one extra step in the current version of the "with-next" folder inside the examples-hub. From my understand is the first one, but I saw another PR raised using the second approach

**Comment by adeets-22** [comment]
Hi @MrRaccxxn! Please feel free to implement it separately so that it is a standalone app cc: @jlm0 for any additional context

**Comment by MrRaccxxn** [comment]
Hello! @jlm0 going through the docs of permissionless and capsule

![Image](https://github.com/user-attachments/assets/61167ae4-2ba8-4bc6-844c-2e3ae846f682)
![Image](https://github.com/user-attachments/assets/19bf4bcb-97bc-4dac-971d-56e6a25b0cf0)

 I encounter one issue at the moment of linking the "smartAccountOwner" to the owner field of toSimpleSmartAccount (The types are different. toSimpleSmartAccount expects a LocalAccount type, and it belongs to another function, createCapsuleAccount from Capsule, that is not included in the documentation).

Trying to use the smartAccountOwner, I get this error because of types:
"Owner account not found."

Using the capsuleAccount variable bypasses this type mismatch but fails in the operation, resulting in:
"Details: UserOperation reverted with reason: AA23 reverted - 0xf645eedf Version: viem@2.22.9
at getBundlerError (getBundlerError.js:102:16)
at eval (getUserOperationError.js:19:91)
at getUserOperationError (getUserOperationError.js:27:7)
at sendUserOperation (sendUserOperation.js:69:108)
at async sendTransaction (sendTransaction.js:71:22)
at async handleSign (with-pimlico.tsx:57:20)Caused by: RpcRequestError: RPC Request failed."

Note: If I skip Capsule and try the same code with privateKeyToAccount from Viem, it works as expected.

**Comment by adeets-22** [comment]
Thank you for surfacing @MrRaccxxn! We are taking a look now

**Comment by adeets-22** [comment]
Hi @MrRaccxxn! Appreciate your patience here, we're a bit backlogged so may take a few days to get back to you. Appreciate all the patience 

This will not impact your ability to get the bounty – we'll be in touch
