### ISSUE TITLE
Example Idea: Capsule + Safe

### ISSUE THREAD

**Issue by adeets-22** [capsule-org/examples-hub#17]
Description: Build a simple example app that uses [Safe](https://safe.global/) for account abstraction and Capsule. Leverage the [Safe example guide](https://docs.usecapsule.com/account-abstraction/safe) to do this.

Use Case: For example, allow users to login with their social accounts via Capsule and enable gas sponsorships or bundled transactions through Safe.

**Comment by mariojere** [comment]
hey can i take on this issue.

**Comment by adeets-22** [comment]
Awesome! Just assigned you

**Comment by mariojere** [comment]
I started this project yesterday and ran some initial tests: (https://capsule-setup-example.vercel.app/). 

Please review and share feedback or required changes i would really like to get more context.

**Comment by jlm0** [comment]
@mariojere Thanks. I'll take a look soon.

**Comment by mariojere** [comment]
i forked the repo and after installing the packages in /with-react-vite and adding the .env variables i am getting the below error when i perform yarn dev

```
/workspaces/examples-hub/web/with-react-vite/node_modules/esbuild/lib/main.js:993
                  reject(new Error(error2));
                         ^

Error: The service was stopped
    at /workspaces/examples-hub/web/with-react-vite/node_modules/esbuild/lib/main.js:993:26
    at responseCallbacks.<computed> (/workspaces/examples-hub/web/with-react-vite/node_modules/esbuild/lib/main.js:622:9)
    at Socket.afterClose (/workspaces/examples-hub/web/with-react-vite/node_modules/esbuild/lib/main.js:613:28)
    at Socket.emit (node:events:530:35)
    at endReadableNT (node:internal/streams/readable:1698:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

Node.js v20.18.1
error Command failed with exit code 1.
```

**Comment by adeets-22** [comment]
@jlm0 can you take a look here?
